package main

import (
	"bytes"
	"go/format"
	"io"
	"text/template"
)

const tmplSrc = `package {{.PName}}

// Code generated by {{.ProgHint}} — DO NOT EDIT.

import (
	"bytes"
	"io"
	"unsafe"
	{{range $pkgname, $pkg := .Imps}}{{if $pkg.Used}}
		{{ $pkgname }} "{{$pkg.ImportPath}}"{{end}}{{end}}
)

{{range .Structs}}
func (me *{{.TName}}) writeTo(buf *bytes.Buffer) (err error) {
	{{if .TmplW}}
	{{.TmplW}}
	{{else}}
	{{if .HasWData}}var data bytes.Buffer{{end}}
	{{if .HasB0Ptr}}var b0 byte ; var b0s = (*((*[1]byte)(unsafe.Pointer(&b0))))[:] {{end}}
	{{if .HasB1Ptr}}var b1 byte = 1 ; var b1s = (*((*[1]byte)(unsafe.Pointer(&b1))))[:] {{end}}
	{{range .Fields}}
	{{.TmplW}}
	{{end}}
	{{end}}
	return
}

func (me *{{.TName}}) WriteTo(w io.Writer) (int64, error) {
	var buf bytes.Buffer
	if err := me.writeTo(&buf); err != nil {
		return 0, err
	}
	return buf.WriteTo(w)
}

func (me *{{.TName}}) MarshalBinary() (data []byte, err error) {
	var buf bytes.Buffer
	if err = me.writeTo(&buf); err == nil {
		data = buf.Bytes()
	}
	return
}

func (me *{{.TName}}) ReadFrom(r io.Reader) (n int64, err error) {
	var buf bytes.Buffer
	if n, err = buf.ReadFrom(r); err == nil {
		err = me.UnmarshalBinary(buf.Bytes())
	}
	return
}

func (me *{{.TName}}) UnmarshalBinary(data []byte) (err error) {
	{{if .TmplR}}
	{{.TmplR}}
	{{else}}
	var p int
	{{range .Fields}}
	{{.TmplR}}
	{{end}}
	{{end}}
	return
}
{{end}}
`

type tmplDotFile struct {
	ProgHint string
	PName    string
	Structs  []*tmplDotStructTypeDef
	Imps     map[string]*tmplDotPkgImp

	allStructTypeDefsCollected bool
}

type tmplDotPkgImp struct {
	ImportPath string
	Used       bool
}

type tmplDotStructTypeDef struct {
	TName    string
	Fields   []*tmplDotField
	HasWData bool
	HasB0Ptr bool
	HasB1Ptr bool
	TmplR    string // only if fixedSize() > 0
	TmplW    string // only if fixedSize() > 0

	fixedsize int
}

func (me *tmplDotStructTypeDef) fixedSize() int {
	if me.fixedsize == 0 && tdot.allStructTypeDefsCollected {
		for _, fld := range me.Fields {
			if fs := fld.fixedSize(); fs < 0 {
				me.fixedsize = -1
				break
			} else if fs == 0 {
				panic("should never occur: " + me.TName + "." + fld.FName)
			} else {
				me.fixedsize += fs
			}
		}
		if me.fixedsize == 0 {
			me.fixedsize = -1
		}
	}
	return me.fixedsize
}

type tmplDotField struct {
	FName string
	TmplW string
	TmplR string

	typeIdent         string
	taggedUnion       []string
	skip              bool
	nextOneWasSkipped bool
	isLast            bool

	fixedsize           int
	fixedsizeExt        int
	fixedsizeExtNumSkip int
}

func (me *tmplDotField) finalTypeIdent() (typeident string) {
	typeident = me.typeIdent
	for tsyn := tSynonyms[typeident]; tsyn != ""; tsyn = tSynonyms[typeident] {
		typeident = tsyn
	}
	return
}

func (me *tmplDotField) fixedSize() int {
	if me.fixedsize == 0 && tdot.allStructTypeDefsCollected {
		me.fixedsize = fixedSizeForTypeSpec(me.typeIdent)
	}
	return me.fixedsize
}

func genViaTmpl(file io.Writer) (err error) {
	tmpl := template.New("gen-tmpl.go")
	if _, err = tmpl.Parse(tmplSrc); err == nil {
		var buf bytes.Buffer
		if err = tmpl.Execute(&buf, &tdot); err == nil {
			src := buf.Bytes()
			if srcfmt, errfmt := format.Source(src); errfmt == nil {
				_, err = file.Write(srcfmt)
			} else {
				_, err = file.Write(src)
			}
		}
	}
	return
}
