package main

type tmplDot struct {
	ProgHint string
	PkgName  string
	TypeName string
}

const tmplPkg = `package {{.PkgName}}
// Code generated by {{.ProgHint}} — DO NOT EDIT.

import (
	"bytes"
)

func (me *{{.TypeName}}) MarshalBinary() (data []byte, err error) {
	var buf bytes.Buffer

	return buf.Bytes(), nil
}

func (me *{{.TypeName}}) UnmarshalBinary(data []byte) error {
	return nil
}
`
